resolver: lts-6.10

packages:
- '.'
- location:
    git: https://github.com/MadSciGuys/FourStore.git
    commit: 388f453adad0b6f0407f221dadbaa2d6591e9a84
- location:
    git: https://github.com/robstewart57/rdf4h
    commit: 9a754d2e7a5b7c60e62f17a0bfcfe34e6e7ee669
- location:
    git: https://github.com/robstewart57/hsparql
    commit: 393c3c39ded78b830f8d14c0c688f2ed3283c8a9
- location: ../xmlrx
#- location: https://hackage.haskell.org/package/ncurses-0.2.15/ncurses-0.2.15.tar.gz 

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: 
- rdf4h-1.3.5
- hsparql-0.2.7
- text-show-instances-2.1
- hgal-2.0.0.2
- attoparsec-0.13.0.1
- text-show-2.1.2
- iso8601-time-0.1.4

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

